In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [2]:
df = pd.read_csv('../data/sierraleone-bumbuna.csv')

# Summary Statistics & Missing-Value Report

In [5]:
df.describe()

,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
mean,201.957515,116.376337,113.720571,206.643095,198.114691,26.319394,79.448857,1.146113,1.691606,0.363823,133.044668,7.172220,999.876469,0.000967,0.004806,32.504263,32.593091,NaN
std,298.495150,218.652659,158.946032,300.896893,288.889073,4.398605,20.520775,1.239248,1.617053,0.295000,114.284792,7.535093,2.104419,0.031074,0.047556,12.434899,12.009161,NaN
min,-19.500000,-7.800000,-17.900000,0.000000,0.000000,12.300000,9.900000,0.000000,0.000000,0.000000,0.000000,0.000000,993.000000,0.000000,0.000000,10.700000,11.100000,NaN
25%,-2.800000,-0.300000,-3.800000,0.000000,0.000000,23.100000,68.700000,0.000000,0.000000,0.000000,0.000000,0.000000,999.000000,0.000000,0.000000,23.500000,23.800000,NaN
50%,0.300000,-0.100000,-0.100000,3.600000,3.400000,25.300000,85.400000,0.800000,1.600000,0.400000,161.500000,6.200000,1000.000000,0.000000,0.000000,26.600000,26.900000,NaN
75%,362.400000,107.000000,224.700000,359.500000,345.400000,29.400000,96.700000,2.000000,2.600000,0.600000,234.100000,12.000000,1001.000000,0.000000,0.000000,40.900000,41.300000,NaN
max,1499.000000,946.000000,892.000000,1507.000000,1473.000000,39.900000,100.000000,19.200000,23.900000,4.100000,360.000000,98.400000,1006.000000,1.000000,2.400000,72.800000,70.400000,NaN

df.isna().sum()

In [7]:
null_percent = df.isna().mean() * 100
cols_with_null = null_percent[null_percent > 5 ]
print(cols_with_null)

Comments    100.0
dtype: float64

# Outlier Detection & Basic Cleaning

In [13]:
df.isna().sum()

Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [16]:
data_cols = ['ModA', 'ModB', 'WS', 'WSgust', 'GHI', "DNI", 'DHI']
for col in data_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(outliers)

               Timestamp    GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
655     2021-10-30 10:56  851.0  285.0  605.9   912.0   890.0  26.0  84.2
658     2021-10-30 10:59  932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00  995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01  988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02  978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
...                  ...    ...    ...    ...     ...     ...   ...   ...
524844  2022-10-29 11:25  888.0  362.7  559.4   932.0   910.0  30.6  77.0
524845  2022-10-29 11:26  986.0  474.4  556.7  1035.0  1009.0  30.7  76.0
524862  2022-10-29 11:43  928.0  400.5  556.8   974.0   949.0  30.0  76.4
524863  2022-10-29 11:44  925.0  396.3  556.9   972.0   946.0  30.2  76.2
524864  2022-10-29 11:45  905.0  385.8  547.0   952.0   927.0  30.3  77.0

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
655     1.6     2.1      0.5   66.4     14.6  1002         0            0.0
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
524844  0.7     1.9      0.7  276.6      5.3  1001         0            0.0
524845  0.2     1.1      0.4   34.4      3.5  1001         0            0.0
524862  0.0     0.4      0.1  338.2      0.0  1000         0            0.0
524863  0.3     1.1      0.5  355.3      4.7  1000         0            0.0
524864  0.1     0.7      0.3  297.3      0.0  1000         0            0.0

        TModA  TModB  Comments
655      52.4   47.0       NaN
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
...       ...    ...       ...
524844   58.5   56.2       NaN
524845   59.2   57.0       NaN
524862   51.0   49.9       NaN
524863   53.3   51.8       NaN
524864   55.2   53.3       NaN

[21017 rows x 19 columns]
               Timestamp    GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
655     2021-10-30 10:56  851.0  285.0  605.9   912.0   890.0  26.0  84.2
658     2021-10-30 10:59  932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00  995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01  988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02  978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
...                  ...    ...    ...    ...     ...     ...   ...   ...
524844  2022-10-29 11:25  888.0  362.7  559.4   932.0   910.0  30.6  77.0
524845  2022-10-29 11:26  986.0  474.4  556.7  1035.0  1009.0  30.7  76.0
524862  2022-10-29 11:43  928.0  400.5  556.8   974.0   949.0  30.0  76.4
524863  2022-10-29 11:44  925.0  396.3  556.9   972.0   946.0  30.2  76.2
524864  2022-10-29 11:45  905.0  385.8  547.0   952.0   927.0  30.3  77.0

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
655     1.6     2.1      0.5   66.4     14.6  1002         0            0.0
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
524844  0.7     1.9      0.7  276.6      5.3  1001         0            0.0
524845  0.2     1.1      0.4   34.4      3.5  1001         0            0.0
524862  0.0     0.4      0.1  338.2      0.0  1000         0            0.0
524863  0.3     1.1      0.5  355.3      4.7  1000         0            0.0
524864  0.1     0.7      0.3  297.3      0.0  1000         0            0.0

        TModA  TModB  Comments
655      52.4   47.0       NaN
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
...       ...    ...       ...
524844   58.5   56.2       NaN
524845   59.2   57.0       NaN
524862   51.0   49.9       NaN
524863   53.3   51.8       NaN
524864   55.2   53.3       NaN

[20613 rows x 19 columns]
               Timestamp    GHI    DNI    DHI   ModA   ModB  Tamb    RH   WS  \
1279    2021-10-30 21:20   -1.0   -0.1   -1.1    0.0    0.0  25.4  81.7  5.1
2495    2021-10-31 17:36   35.2    3.6   34.3   35.1   33.1  31.2  66.8  7.5
2496    2021-10-31 17:37   28.9    0.3   29.0   30.8   29.0  30.9  66.7  6.2
2497    2021-10-31 17:38   26.0    0.2   26.2   29.3   27.8  30.6  63.6  5.2
2498    2021-10-31 17:39   24.6    0.2   24.8   28.9   27.4  30.2  63.6  5.3
...                  ...    ...    ...    ...    ...    ...   ...   ...  ...
519313  2022-10-25 15:14  699.6  718.6  187.4  711.6  697.8  34.8  51.1  5.4
519396  2022-10-25 16:37  365.7  516.2  139.6  346.0  339.5  34.1  51.0  5.2
522183  2022-10-27 15:04  179.5   -0.5  177.6  177.1  170.0  30.5  68.8  5.2
522184  2022-10-27 15:05  167.2   -0.5  165.1  167.6  160.9  30.4  68.3  5.3
522185  2022-10-27 15:06  163.4   -0.6  161.0  165.7  159.2  30.2  67.7  7.1

        WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  TModA  \
1279       6.2      1.1   75.8     19.5  1004         0            0.0   25.8
2495       9.7      1.3  138.2     27.2   999         0            0.0   37.6
2496       7.9      0.9  111.9     15.5   999         0            0.0   36.4
2497       7.2      1.0   99.4     20.3   999         0            0.0   35.1
2498       7.4      1.3  101.5     18.6   999         0            0.0   34.1
...        ...      ...    ...      ...   ...       ...            ...    ...
519313     6.7      0.7   73.3      8.9   996         0            0.0   55.5
519396     6.9      1.2   68.1     16.4   996         0            0.0   47.8
522183     7.2      1.0  150.3     10.4   999         0            0.0   37.2
522184     6.7      0.9  147.9     10.1   999         0            0.0   36.4
522185     8.4      0.8  144.5      7.7   999         0            0.0   35.6

        TModB  Comments
1279     26.3       NaN
2495     39.0       NaN
2496     37.4       NaN
2497     35.9       NaN
2498     34.6       NaN
...       ...       ...
519313   54.2       NaN
519396   50.0       NaN
522183   37.3       NaN
522184   36.4       NaN
522185   35.6       NaN

[3169 rows x 19 columns]
               Timestamp    GHI    DNI    DHI   ModA   ModB  Tamb    RH   WS  \
1275    2021-10-30 21:16   -0.7    0.0   -0.9    0.0    0.0  25.2  86.8  4.0
1287    2021-10-30 21:28   -1.8   -1.8   -1.5    0.0    0.0  24.4  83.6  4.7
2495    2021-10-31 17:36   35.2    3.6   34.3   35.1   33.1  31.2  66.8  7.5
2496    2021-10-31 17:37   28.9    0.3   29.0   30.8   29.0  30.9  66.7  6.2
2497    2021-10-31 17:38   26.0    0.2   26.2   29.3   27.8  30.6  63.6  5.2
...                  ...    ...    ...    ...    ...    ...   ...   ...  ...
519396  2022-10-25 16:37  365.7  516.2  139.6  346.0  339.5  34.1  51.0  5.2
522183  2022-10-27 15:04  179.5   -0.5  177.6  177.1  170.0  30.5  68.8  5.2
522184  2022-10-27 15:05  167.2   -0.5  165.1  167.6  160.9  30.4  68.3  5.3
522185  2022-10-27 15:06  163.4   -0.6  161.0  165.7  159.2  30.2  67.7  7.1
523794  2022-10-28 17:55   22.8   -0.8   21.4   26.5   25.0  27.9  80.4  5.0

        WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  TModA  \
1275       6.7      1.4   98.6     19.4  1004         0            0.0   25.6
1287       6.7      1.4   62.6     11.5  1004         0            0.7   23.9
2495       9.7      1.3  138.2     27.2   999         0            0.0   37.6
2496       7.9      0.9  111.9     15.5   999         0            0.0   36.4
2497       7.2      1.0   99.4     20.3   999         0            0.0   35.1
...        ...      ...    ...      ...   ...       ...            ...    ...
519396     6.9      1.2   68.1     16.4   996         0            0.0   47.8
522183     7.2      1.0  150.3     10.4   999         0            0.0   37.2
522184     6.7      0.9  147.9     10.1   999         0            0.0   36.4
522185     8.4      0.8  144.5      7.7   999         0            0.0   35.6
523794     6.7      1.0   21.4     18.1   999         0            0.0   30.5

        TModB  Comments
1275     26.1       NaN
1287     24.1       NaN
2495     39.0       NaN
2496     37.4       NaN
2497     35.9       NaN
...       ...       ...
519396   50.0       NaN
522183   37.3       NaN
522184   36.4       NaN
522185   35.6       NaN
523794   30.6       NaN

[3665 rows x 19 columns]
               Timestamp     GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
658     2021-10-30 10:59   932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00   995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01   988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02   978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
662     2021-10-30 11:03  1071.0  616.0  539.1  1142.0  1116.0  26.4  82.5
...                  ...     ...    ...    ...     ...     ...   ...   ...
524842  2022-10-29 11:23   931.0  446.7  529.0   979.0   953.0  30.7  75.1
524843  2022-10-29 11:24   955.0  455.5  544.3   999.0   974.0  30.7  75.4
524845  2022-10-29 11:26   986.0  474.4  556.7  1035.0  1009.0  30.7  76.0
524862  2022-10-29 11:43   928.0  400.5  556.8   974.0   949.0  30.0  76.4
524863  2022-10-29 11:44   925.0  396.3  556.9   972.0   946.0  30.2  76.2

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
662     0.2     0.7      0.4   20.2     11.9  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
524842  0.5     1.6      0.7  244.8      7.8  1001         0            0.0
524843  0.8     1.9      0.7  256.0     10.2  1001         0            0.0
524845  0.2     1.1      0.4   34.4      3.5  1001         0            0.0
524862  0.0     0.4      0.1  338.2      0.0  1000         0            0.0
524863  0.3     1.1      0.5  355.3      4.7  1000         0            0.0

        TModA  TModB  Comments
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
662      59.3   51.8       NaN
...       ...    ...       ...
524842   56.7   54.2       NaN
524843   57.9   55.3       NaN
524845   59.2   57.0       NaN
524862   51.0   49.9       NaN
524863   53.3   51.8       NaN

[15853 rows x 19 columns]
               Timestamp    GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
655     2021-10-30 10:56  851.0  285.0  605.9   912.0   890.0  26.0  84.2
658     2021-10-30 10:59  932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00  995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01  988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02  978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
...                  ...    ...    ...    ...     ...     ...   ...   ...
525038  2022-10-29 14:39  542.7  279.0  319.5   563.4   549.4  30.6  75.9
525039  2022-10-29 14:40  553.1  285.1  325.7   573.4   559.1  30.7  76.9
525040  2022-10-29 14:41  581.4  315.8  330.6   602.5   587.4  30.8  75.9
525041  2022-10-29 14:42  583.0  315.6  333.2   602.8   587.5  30.9  76.3
525042  2022-10-29 14:43  576.6  309.7  332.1   595.3   580.3  31.0  75.3

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
655     1.6     2.1      0.5   66.4     14.6  1002         0            0.0
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
525038  1.0     1.9      0.4  236.7      7.1   998         0            0.0
525039  1.3     1.9      0.4  240.2      7.1   997         0            0.0
525040  1.2     2.1      0.7  232.2     12.3   997         0            0.0
525041  1.6     2.4      0.7  204.2     13.2   997         0            0.0
525042  2.4     3.4      0.6  204.1     10.9   997         0            0.0

        TModA  TModB  Comments
655      52.4   47.0       NaN
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
...       ...    ...       ...
525038   43.6   46.6       NaN
525039   44.5   47.5       NaN
525040   45.3   48.4       NaN
525041   46.3   49.3       NaN
525042   47.3   50.1       NaN

[101688 rows x 19 columns]
               Timestamp    GHI    DNI    DHI   ModA   ModB  Tamb    RH   WS  \
651     2021-10-30 10:52  664.2  108.2  569.6  706.3  689.3  25.9  84.3  0.8
652     2021-10-30 10:53  718.3  155.5  584.1  767.6  748.9  25.9  85.5  0.2
653     2021-10-30 10:54  814.0  257.0  594.3  878.0  856.0  25.9  85.3  0.5
654     2021-10-30 10:55  826.0  263.5  599.6  883.0  861.0  26.0  85.4  1.7
655     2021-10-30 10:56  851.0  285.0  605.9  912.0  890.0  26.0  84.2  1.6
...                  ...    ...    ...    ...    ...    ...   ...   ...  ...
517730  2022-10-24 12:51  751.5  103.2  645.6  764.9  746.8  30.1  73.1  1.9
517731  2022-10-24 12:52  748.0  120.9  625.9  759.9  741.8  30.0  72.9  1.8
517732  2022-10-24 12:53  676.9   72.6  603.5  683.0  666.3  30.0  72.8  2.0
517733  2022-10-24 12:54  636.7   51.4  585.1  639.7  624.0  29.9  72.6  1.8
517734  2022-10-24 12:55  613.9   43.0  571.4  616.0  601.2  29.9  76.3  1.6

        WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  TModA  \
651        1.6      0.6   58.5      9.6  1002         0            0.0   49.0
652        1.1      0.4   87.2      0.4  1002         0            0.0   49.4
653        1.1      0.5   81.4      7.9  1002         0            0.0   50.4
654        2.4      0.4   74.6     12.1  1002         0            0.0   51.6
655        2.1      0.5   66.4     14.6  1002         0            0.0   52.4
...        ...      ...    ...      ...   ...       ...            ...    ...
517730     2.4      0.4  236.7     11.6  1001         0            0.0   55.0
517731     2.4      0.4  232.0     12.1  1001         0            0.0   54.8
517732     2.6      0.5  241.8     19.4  1001         0            0.0   54.7
517733     2.4      0.4  250.0     19.0  1001         0            0.0   54.5
517734     2.4      0.4  290.1     20.5  1001         0            0.0   54.2

        TModB  Comments
651      44.6       NaN
652      44.8       NaN
653      45.6       NaN
654      46.6       NaN
655      47.0       NaN
...       ...       ...
517730   57.2       NaN
517731   56.7       NaN
517732   56.2       NaN
517733   55.7       NaN
517734   55.2       NaN

[4407 rows x 19 columns]

### z-scores

In [18]:
key_cols = ['GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'WS', 'WSgust']
mean = df[key_cols].mean()
std = df[key_cols].std()
z_score = (df[key_cols] - mean) / std
z_score

             GHI       DNI       DHI      ModA      ModB        WS    WSgust
0      -0.678931 -0.532700 -0.720500 -0.686757 -0.685781 -0.924845 -1.046104
1      -0.678931 -0.532700 -0.720500 -0.686757 -0.685781 -0.924845 -1.046104
2      -0.678931 -0.532700 -0.720500 -0.686757 -0.685781 -0.924845 -1.046104
3      -0.678931 -0.532243 -0.720500 -0.686757 -0.685781 -0.924845 -1.046104
4      -0.678931 -0.532700 -0.720500 -0.686757 -0.685781 -0.924845 -1.046104
...          ...       ...       ...       ...       ...       ...       ...
525595 -0.681946 -0.532700 -0.733712 -0.686757 -0.685781 -0.924845 -1.046104
525596 -0.682281 -0.532700 -0.734341 -0.686757 -0.685781 -0.924845 -1.046104
525597 -0.682281 -0.532700 -0.734970 -0.686757 -0.685781 -0.924845 -1.046104
525598 -0.682281 -0.533158 -0.736228 -0.686757 -0.685781 -0.924845 -1.046104
525599 -0.682281 -0.532700 -0.736857 -0.686757 -0.685781 -0.924845 -1.046104

[525600 rows x 7 columns]

In [20]:
outliers_three = abs(z_score) > 3
rows_with_outlier = df[outliers_three.any(axis=1)]
rows_with_outlier

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
653,2021-10-30 10:54,814.0,257.0,594.3,878.0,856.0,25.9,85.3,0.5,1.1,0.5,81.4,7.9,1002,0,0.0,50.4,45.6,NaN
654,2021-10-30 10:55,826.0,263.5,599.6,883.0,861.0,26.0,85.4,1.7,2.4,0.4,74.6,12.1,1002,0,0.0,51.6,46.6,NaN
655,2021-10-30 10:56,851.0,285.0,605.9,912.0,890.0,26.0,84.2,1.6,2.1,0.5,66.4,14.6,1002,0,0.0,52.4,47.0,NaN
656,2021-10-30 10:57,823.0,254.8,603.9,878.0,856.0,26.0,85.3,0.8,1.6,0.6,90.2,7.0,1002,0,0.0,53.4,47.7,NaN
657,2021-10-30 10:58,810.0,244.5,598.8,864.0,843.0,26.1,85.7,0.6,1.6,0.6,108.5,7.9,1002,0,0.0,54.6,48.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522184,2022-10-27 15:05,167.2,-0.5,165.1,167.6,160.9,30.4,68.3,5.3,6.7,0.9,147.9,10.1,999,0,0.0,36.4,36.4,NaN
522185,2022-10-27 15:06,163.4,-0.6,161.0,165.7,159.2,30.2,67.7,7.1,8.4,0.8,144.5,7.7,999,0,0.0,35.6,35.6,NaN
522194,2022-10-27 15:15,183.5,0.3,181.6,173.7,168.7,29.3,70.2,4.9,5.9,0.7,128.7,14.9,999,0,0.0,35.3,35.1,NaN
523792,2022-10-28 17:53,31.3,-0.5,30.2,34.3,32.3,28.4,79.5,5.0,6.4,0.9,354.4,22.9,999,0,0.0,31.3,31.4,NaN
523794,2022-10-28 17:55,22.8,-0.8,21.4,26.5,25.0,27.9,80.4,5.0,6.7,1.0,21.4,18.1,999,0,0.0,30.5,30.6,NaN

### impute (median) missing values in key columns

In [23]:
key_cols = ['GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'WS', 'WSgust']
median = df[key_cols].median()
df[key_cols] = df[key_cols].fillna(median)

In [24]:
df.isna().sum()

Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

### export

In [26]:
df.to_csv("../data/sierraleone-bumbuna_clean.csv")